version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    # Group all patch and minor updates into a single PR
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Allow up to 5 open pull requests for npm dependencies
    open-pull-requests-limit: 5
    # Add reviewers and assignees
    reviewers:
      - "belas" # Replace with your GitHub username
    # Add labels to dependency PRs
    labels:
      - "dependencies"
      - "automated"
    # Commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Target branch
    target-branch: "main"
    # Rebase strategy
    rebase-strategy: "auto"
    # Allow Dependabot to resolve conflicts
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore specific dependencies (if needed)
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
    # Group all GitHub Actions updates
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "belas" # Replace with your GitHub username
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"